version: '3.7'

services:
  db:
    container_name: neoway_db
    image: postgres:15.0
    restart: always
    env_file:
      - ./api/.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      PGDATA: /data/postgres
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_PORT:5432
    networks:
      - neoway.challenge
  api:
    build:
      context: api/.
    container_name: neoway_api
    # restart: always
    env_file:
      - ./api/.env
    environment:
      # When run with docker, DB_HOST must be exactly container_name of the db service(eg: neoway_db).
      - WAIT_HOSTS=$DB_HOST:5432
    ports:
      - $SERVER_PORT:4444
    networks:
      - neoway.challenge
    depends_on:
      - db
networks:
  neoway.challenge:
    driver: 'bridge'
